export const songLyrics: Record<string, { time: number; text: string }[]> = {
  'Natsu O Dakishimete': [
    { time: 0, text: '♪ (Instrumental Intro) ♪' },
    { time: 15, text: 'Natsu o dakishimete' },
    { time: 20, text: 'Atsui kisetsu ga yatte kita' },
    { time: 25, text: 'Shiroi sunahama, aoi umi' },
    { time: 30, text: 'Kimi to issho ni sugoshitai' },
    { time: 45, text: 'Taiyou ga mabushikute' },
    { time: 50, text: 'Kaze ga kimochi iine' },
    { time: 55, text: 'Zutto kono mama de itai' },
    { time: 60, text: 'Natsu no omoide tsukurou' },
  ],
  'Midnight City': [
    { time: 0, text: '♪ (Synth Intro) ♪' },
    { time: 20, text: 'Waiting in a car' },
    { time: 25, text: 'Waiting for a ride in the dark' },
    { time: 30, text: 'The night city grows' },
    { time: 35, text: 'Look and see her eyes, they glow' },
    { time: 50, text: 'Waiting in a car' },
    { time: 55, text: 'Waiting for a ride in the dark' },
    { time: 60, text: 'Drinking in the lounge' },
    { time: 65, text: 'Following the neon signs' },
  ],
  'Autumn Leaves': [
    { time: 0, text: '♪ (Instrumental Jazz) ♪' },
    { time: 10, text: '♪ (Trumpet Solo) ♪' },
    { time: 40, text: '♪ (Piano Solo) ♪' },
    { time: 80, text: '♪ (Bass Solo) ♪' },
  ],
  'Everlong': [
    { time: 0, text: '♪ (Guitar Intro) ♪' },
    { time: 20, text: 'Hello, I\'ve waited here for you' },
    { time: 25, text: 'Everlong' },
    { time: 30, text: 'Tonight, I throw myself into' },
    { time: 35, text: 'And out of the red' },
    { time: 40, text: 'Out of her head, she sang' },
    { time: 48, text: 'Come down and waste away with me' },
    { time: 53, text: 'Down with me' },
    { time: 58, text: 'Slow, how you wanted it to be' },
  ],
  'Superstition': [
    { time: 0, text: '♪ (Clavinet & Drum Intro) ♪' },
    { time: 26, text: 'Very superstitious' },
    { time: 29, text: 'Writing\'s on the wall' },
    { time: 34, text: 'Very superstitious' },
    { time: 37, text: 'Ladders \'bout to fall' },
    { time: 42, text: 'Thirteen month old baby' },
    { time: 45, text: 'Broke the lookin\' glass' },
    { time: 50, text: 'Seven years of bad luck' },
    { time: 53, text: 'The good things in your past' },
    { time: 58, text: 'When you believe in things that you don\'t understand' },
    { time: 63, text: 'Then you suffer' },
    { time: 66, text: 'Superstition ain\'t the way' },
  ],
  'Neon': [
    { time: 0, text: '♪ (Acoustic Guitar Intro) ♪' },
    { time: 30, text: 'When sky blue gets dark enough' },
    { time: 34, text: 'To see the colors of the city lights' },
    { time: 39, text: 'A trail of ruby red and diamond white' },
    { time: 43, text: 'Hits her like a sunrise' },
    { time: 48, text: 'She comes and goes and comes and goes' },
    { time: 52, text: 'Like no one can' },
    { time: 57, text: 'She comes and goes and no one knows' },
    { time: 61, text: 'She\'s slipping through my hands' },
    { time: 65, text: 'She\'s always buzzing just like neon, neon' },
  ],
  'Texas Flood': [
    { time: 0, text: '♪ (Blues Guitar Intro) ♪' },
    { time: 45, text: 'Well there\'s floodin\' down in Texas' },
    { time: 52, text: 'All of the telephone lines are down' },
    { time: 60, text: 'Well there\'s floodin\' down in Texas' },
    { time: 67, text: 'All of the telephone lines are down' },
    { time: 76, text: 'And I\'ve been tryin\' to call my baby' },
    { time: 83, text: 'Lord and I can\'t get a single sound' },
  ],
  'Master of Puppets': [
    { time: 0, text: '♪ (Heavy Metal Riff) ♪' },
    { time: 55, text: 'End of passion play' },
    { time: 58, text: 'Crumbling away' },
    { time: 62, text: 'I\'m your source of self-destruction' },
    { time: 66, text: 'Veins that pump with fear' },
    { time: 69, text: 'Sucking darkest clear' },
    { time: 73, text: 'Leading on your death\'s construction' },
    { time: 77, text: 'Taste me you will see' },
    { time: 80, text: 'More is all you need' },
    { time: 84, text: 'Dedicated to' },
    { time: 87, text: 'How I\'m killing you' },
    { time: 91, text: 'Come crawling faster' },
    { time: 96, text: 'Obey your master' },
  ],
  'Jolene': [
    { time: 0, text: '♪ (Acoustic Guitar Intro) ♪' },
    { time: 12, text: 'Jolene, Jolene, Jolene, Jolene' },
    { time: 17, text: 'I\'m begging of you please don\'t take my man' },
    { time: 24, text: 'Jolene, Jolene, Jolene, Jolene' },
    { time: 29, text: 'Please don\'t take him just because you can' },
    { time: 37, text: 'Your beauty is beyond compare' },
    { time: 40, text: 'With flaming locks of auburn hair' },
    { time: 43, text: 'With ivory skin and eyes of emerald green' },
  ],
  'Redbone': [
    { time: 0, text: '♪ (Funk Intro) ♪' },
    { time: 35, text: 'Daylight' },
    { time: 39, text: 'I wake up feeling like you won\'t play right' },
    { time: 45, text: 'I used to know, but now that shit don\'t feel right' },
    { time: 52, text: 'It made me put away my pride' },
    { time: 58, text: 'So long' },
    { time: 62, text: 'You made a nigga wait for some, so long' },
    { time: 69, text: 'You make it hard for boy like that to go on' },
    { time: 75, text: 'I\'m wishing I could make this mine, oh' },
    { time: 82, text: 'If you want it, yeah' },
    { time: 86, text: 'You can have it, oh, oh, oh' },
    { time: 90, text: 'If you need it, ooh' },
    { time: 94, text: 'We can make it, oh' },
    { time: 97, text: 'If you want it' },
    { time: 101, text: 'You can have it' },
  ]
};
